### ISSUE TITLE
Hardcoded path to a missing font

### ISSUE THREAD

**Issue by reshen** [Adamekka/bevy-fps-counter#1]
Hi there,

There is a hardcoded path to a non-default font at https://github.com/Adamekka/bevy-fps-counter/blob/54fe5c64c819914437987329054a47d922b83ffc/src/lib.rs#L115 which prevents this crate from working without a bit more work.

Bevy has a default font now, see [0.11 release notes](https://bevyengine.org/news/bevy-0-11/#default-font) and here is an [example of it in use](https://bevyengine.org/examples/UI%20(User%20Interface)/text/).  Any chance you can update the code to use the default if the custom one is unavailable?  At any rate, thanks for the plugin!

Thanks!

**Comment by Adamekka** [comment]
sure, gonna look into that
